services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: webcrawler_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []
