# docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: webcrawler_api
    ports:
      - "8000:8000"       # FastAPI port
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: webcrawler_worker
    command: celery -A app.scheduler.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: webcrawler_beat
    command: celery -A app.scheduler.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: webcrawler_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: webcrawler_redis
    ports:
      - "6380:6379"

volumes:
  mongo_data:
